# Jekyll Configuration
title: Zhanglong Cao
description: Statistics, Agricultural Data Analytics, and Research in Biometry
url: "https://jeromecy.github.io"
baseurl: ""

# Author information
author:
  name: Dr. Zhanglong Cao
  github: jeromecy
  twitter: JeromeCY
  linkedin: zhanglong-cao-72208487
  email: cao.zhanglong@gmail.com
  bio: Statistician, Biometrician
  email_md5: 9f00102e0a362e3a92ccefd0d35c6e5d

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Description
description: This is my homepage for sharing knowledge and experience.



# RSS and category paths
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

# BASE_PATH
BASE_PATH:
